<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LOQ4435" ignored="1" name="Personal Loan" tests="5" failures="1" timestamp="20 Apr 2019 07:14:52 GMT" time="0.113" errors="0">
  <testcase name="Demo" time="0.031" classname="Test.Day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Day1.Demo(Day1.java:18)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="ploan" time="0.003" classname="Test.Day2"/>
  <testcase name="LoginAPIHomeLoan" time="0.002" classname="Test.Day4"/>
  <testcase name="MobileloginHomeLoan" time="0.004" classname="Test.Day4"/>
  <testcase name="WebloginHomeLoan" time="0.003" classname="Test.Day4"/>
  <testcase name="SecondTest" time="0.0" classname="Test.Day1">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
